language: nodejs

node_js: 8.12.0

cache:
  directories:
  - node_modules

before_script:
- npm install
- npm run build

script:
- npm run test
- npm run test:coveralls

after_success:
- npm pack

deploy:
- provider: pages
  skip_cleanup: true
  local_dir: docs/
  github_token: $GITHUB_TOKEN
  on:
    tags: true
- provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "{when-ts}-*.tgz"
  skip_cleanup: true
  on:
    tags: true
- provider: npm
  email: voodooattack@hotmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    repo: voodooattack/when-ts
